=== Cortes-cmd/LenguajeDeMarcas/2ºTrimestre/Primeros_Pasos_XML/Tarea repaso - XML/notas.dtd
<!ELEMENT notas (alumno+)>
<!ELEMENT alumno (nota1, nota2, nota3, media)>
<!ELEMENT nota1 (#PCDATA)>
<!ELEMENT nota2 (#PCDATA)>
<!ELEMENT nota3 (#PCDATA)>
<!ELEMENT media (#PCDATA)>

=== Cortes-cmd/LenguajeDeMarcas/2ºTrimestre/Primeros_Pasos_XML/Tarea repaso - XML/notas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="notas.xsl"?>
<!DOCTYPE notas SYSTEM "C:\Users\PcCom\Documents\GitHub\LenguajeDeMarcas\2ºTrimestre\Primeros_Pasos_XML\Tarea repaso - XML\notas.dtd">
<notas>
    <alumno>
        <nota1>5</nota1>
        <nota2>7</nota2>
        <nota3>4.5</nota3>
        <media>5.5</media>
    </alumno>
    <alumno>
        <nota1>10</nota1>
        <nota2>2</nota2>
        <nota3>8</nota3>
        <media>6.66</media>
    </alumno>
    <alumno>
        <nota1>6.5</nota1>
        <nota2>7.5</nota2>
        <nota3>7</nota3>
        <media>7</media>
    </alumno>
</notas>

=== Cortes-cmd/LenguajeDeMarcas/2ºTrimestre/Practico/Repaso/notas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:/C:/Users/CampusFP/Documents/Git/MiPrimerRepo/LenguajeDeMarcas/2%C2%BATrimestre/Primeros_Pasos_XML/Tarea%20repaso%20-%20XML/notas.xsl"?>
<!DOCTYPE notas SYSTEM "file:/C:/Users/CampusFP/Documents/Git/MiPrimerRepo/LenguajeDeMarcas/2%C2%BATrimestre/Primeros_Pasos_XML/Tarea%20repaso%20-%20XML/notas.dtd">
<notas>
    <alumno>
        <nota1>5</nota1>
        <nota2>7</nota2>
        <nota3>4.5</nota3>
        <media>5.5</media>
    </alumno>
    <alumno>
        <nota1>10</nota1>
        <nota2>2</nota2>
        <nota3>8</nota3>
        <media>6.66</media>
    </alumno>
    <alumno>
        <nota1>6.5</nota1>
        <nota2>7.5</nota2>
        <nota3>7</nota3>
        <media>7</media>
    </alumno>
</notas>
